import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  type CsvCardRow,
  validateAndReportCsvRows,
} from "./validate.js";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDirectory, "..");
const inputPath = resolve(projectRoot, "data-source/cards.csv");
const outputPath = resolve(projectRoot, "src/data/cards.ts");

function parseCsv(csv: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let value = "";
  let inQuotes = false;

  for (let index = 0; index < csv.length; index += 1) {
    const character = csv[index];

    if (character === '"') {
      if (inQuotes && csv[index + 1] === '"') {
        value += '"';
        index += 1;
      } else {
        inQuotes = !inQuotes;
      }

      continue;
    }

    if (!inQuotes && character === ",") {
      row.push(value);
      value = "";
      continue;
    }

    if (!inQuotes && (character === "\n" || character === "\r")) {
      if (character === "\r" && csv[index + 1] === "\n") {
        index += 1;
      }

      row.push(value);
      rows.push(row);
      row = [];
      value = "";
      continue;
    }

    value += character;
  }

  if (inQuotes) {
    throw new Error("CSV contains an unclosed quoted value.");
  }

  if (value || row.length > 0) {
    row.push(value);
    rows.push(row);
  }

  return rows;
}

function toCsvRows(csv: string): CsvCardRow[] {
  const [header = [], ...records] = parseCsv(csv);
  const columns = header.map((column) => column.trim());

  return records.map((record) =>
    columns.reduce<CsvCardRow>((row, column, index) => {
      row[column as keyof CsvCardRow] = record[index] ?? "";
      return row;
    }, {})
  );
}

function renderCards(rows: CsvCardRow[]): string {
  const cards = rows
    .map((row) => ({
      id: Number(row.id),
      type: String(row.type).trim(),
      content: String(row.content).trim(),
    }))
    .sort((left, right) => left.id - right.id);

  const cardEntries = cards.map(
    (card) => [
      "  {",
      `    id: ${card.id},`,
      `    type: ${JSON.stringify(card.type)},`,
      `    content: ${JSON.stringify(card.content)},`,
      "  },",
    ].join("\n")
  );

  return [
    "/**",
    " * AUTO-GENERATED FILE.",
    " * DO NOT EDIT.",
    " * Generated by:",
    " * npm run export:cards",
    " */",
    "",
    'import type { Card } from "../types/card";',
    "",
    "export const cards: Card[] = [",
    ...cardEntries,
    "];",
    "",
  ].join("\n");
}

function fail(message: string): void {
  console.error(`Card export failed: ${message}`);
  process.exitCode = 1;
}

function main(): void {
  let rows: CsvCardRow[];

  try {
    const csv = readFileSync(inputPath, "utf8");
    rows = toCsvRows(csv);
  } catch (error) {
    fail(error instanceof Error ? error.message : String(error));
    return;
  }

  if (!validateAndReportCsvRows(rows)) {
    return;
  }

  writeFileSync(outputPath, renderCards(rows), "utf8");
}

main();
