/**
 * AUTO-GENERATED FILE.
 * DO NOT EDIT.
 * Generated by:
 * npm run export:cards
 */

import type { Card } from "../types/card";

export const cards: Card[] = [
  {
    id: 1,
    type: "truth",
    content: "Ai trong bàn là người bạn nghĩ uống giỏi nhất?",
  },
  {
    id: 2,
    type: "truth",
    content: "Nếu được miễn uống cả tối nay, bạn sẽ nhường quyền đó cho ai?",
  },
  {
    id: 3,
    type: "truth",
    content: "Lần say gần đây nhất của bạn diễn ra ở đâu?",
  },
  {
    id: 4,
    type: "truth",
    content: "Món nhậu bạn thích nhất là gì?",
  },
  {
    id: 5,
    type: "truth",
    content: "Nếu phải rủ một người trong bàn đi du lịch, bạn sẽ chọn ai?",
  },
  {
    id: 6,
    type: "truth",
    content: "Ai trong bàn có gu ăn mặc đẹp nhất?",
  },
  {
    id: 7,
    type: "truth",
    content: "Theo bạn ai trong bàn quậy nhất khi có bia rượu?",
  },
  {
    id: 8,
    type: "truth",
    content: "Bạn thích nhất bộ phận nào trên cơ thể mình?",
  },
  {
    id: 9,
    type: "truth",
    content: "Lâu nhất bạn từng không tắm là bao lâu?",
  },
  {
    id: 10,
    type: "truth",
    content: "Theo bạn ai trong bàn hài hước nhất?",
  },
  {
    id: 11,
    type: "truth",
    content: "Ai trong bàn có khả năng làm leader tốt nhất?",
  },
  {
    id: 12,
    type: "truth",
    content: "Nếu mở một quán nhậu, bạn sẽ rủ ai góp vốn?",
  },
  {
    id: 13,
    type: "truth",
    content: "Ai trong bàn có gu âm nhạc hợp bạn nhất?",
  },
  {
    id: 14,
    type: "truth",
    content: "Bạn thích bia, cocktail hay rượu mạnh hơn?",
  },
  {
    id: 15,
    type: "truth",
    content: "Ai trong bàn có khả năng giữ bí mật tốt nhất?",
  },
  {
    id: 16,
    type: "truth",
    content: "Thói quen/ hành động gì ở đối phương khiến bạn lập tức say bye?",
  },
  {
    id: 17,
    type: "truth",
    content: "Ai trong bàn có nụ cười đẹp nhất?",
  },
  {
    id: 18,
    type: "truth",
    content: "Nếu được đổi chỗ với một người ngay bây giờ, bạn sẽ chọn ai?",
  },
  {
    id: 19,
    type: "truth",
    content: "Ai trong bàn có vẻ là người khó say nhất?",
  },
  {
    id: 20,
    type: "truth",
    content: "Bạn muốn gặp lại ai trong bàn ở buổi nhậu tiếp theo?",
  },
  {
    id: 21,
    type: "dare",
    content: "Uống một nửa ly.",
  },
  {
    id: 22,
    type: "dare",
    content: "Chọn một người cùng cụng ly và cả hai cùng uống.",
  },
  {
    id: 23,
    type: "dare",
    content: "Uống 1 ly",
  },
  {
    id: 24,
    type: "dare",
    content: "Mời cả bàn nâng ly rồi bạn uống đầu tiên.",
  },
  {
    id: 25,
    type: "dare",
    content: "Để người bên phải đúc cho bạn uống.",
  },
  {
    id: 26,
    type: "dare",
    content: "Nói chuyện bằng giọng em bé trong 30 giây.",
  },
  {
    id: 27,
    type: "dare",
    content: "Catwalk một vòng quanh bàn.",
  },
  {
    id: 28,
    type: "dare",
    content: "Bắt chước tiếng cười của người đối diện.",
  },
  {
    id: 29,
    type: "dare",
    content: "Diễn tả một bộ phim để cả bàn đoán.",
  },
  {
    id: 30,
    type: "dare",
    content: "Hát điệp khúc bài hát bất kỳ.",
  },
  {
    id: 31,
    type: "dare",
    content: "Hôn 1 cái ở cổ người bên phải.",
  },
  {
    id: 32,
    type: "dare",
    content: "Bắt tay với tất cả mọi người.",
  },
  {
    id: 33,
    type: "dare",
    content: "Để cả bàn đặt cho bạn một biệt danh.",
  },
  {
    id: 34,
    type: "dare",
    content: "Khen người bên trái bằng ba từ.",
  },
  {
    id: 35,
    type: "dare",
    content: "Nhìn vào mắt người đối diện trong 10 giây.",
  },
  {
    id: 36,
    type: "dare",
    content: "Khoác vai người bên cạnh trong 10 giây.",
  },
  {
    id: 37,
    type: "dare",
    content: "Hôn trán người đối diện.",
  },
  {
    id: 38,
    type: "dare",
    content: "Ôm người bạn chọn trong 5 giây.",
  },
  {
    id: 39,
    type: "dare",
    content: "Hôn lên mu... bàn tay người được chỉ định.",
  },
  {
    id: 40,
    type: "dare",
    content: "Chạm trán với người bên cạnh trong 5 giây.",
  },
  {
    id: 41,
    type: "random",
    content: "Tất cả cùng uống một ly.",
  },
  {
    id: 42,
    type: "random",
    content: "Người mặc áo tối màu uống.",
  },
  {
    id: 43,
    type: "random",
    content: "Người đeo kính uống.",
  },
  {
    id: 44,
    type: "random",
    content: "Tất cả đổi chỗ ngồi.",
  },
  {
    id: 45,
    type: "random",
    content: "Cụng ly với người bên trái.",
  },
  {
    id: 46,
    type: "random",
    content: "Cả bàn phải cười trong 5 giây.",
  },
  {
    id: 47,
    type: "random",
    content: "Ai cười đầu tiên uống.",
  },
  {
    id: 48,
    type: "random",
    content: "Mọi người đổi chỗ điện thoại cho nhau trong 10 giây (không mở khóa).",
  },
  {
    id: 49,
    type: "random",
    content: "Ai mặc áo sáng màu uống.",
  },
  {
    id: 50,
    type: "random",
    content: "Mỗi người nói một lời khen cho người bên trái.",
  },
  {
    id: 51,
    type: "truth",
    content: "Ai trong bàn có 'red flag' rõ nhất?",
  },
  {
    id: 52,
    type: "truth",
    content: "Ai có vibe người yêu lý tưởng nhất?",
  },
  {
    id: 53,
    type: "truth",
    content: "Nếu phải unfollow một người trong bàn, bạn chọn ai?",
  },
  {
    id: 54,
    type: "truth",
    content: "Ai nhìn hiền nhưng đáng nghi nhất?",
  },
  {
    id: 55,
    type: "truth",
    content: "Ai có khả năng ghost tin nhắn nhất?",
  },
  {
    id: 56,
    type: "truth",
    content: "Nếu phải hôn ngay một người lúc này, bạn sẽ chọn ai?",
  },
  {
    id: 57,
    type: "truth",
    content: "Ai dễ viral trên TikTok nhất?",
  },
  {
    id: 58,
    type: "truth",
    content: "Ai sẽ là người cưới sớm nhất?",
  },
  {
    id: 59,
    type: "truth",
    content: "Bạn đã từng rung động với người lớn tuổi hoặc nhỏ tuổi hơn mình rất nhiều chưa?",
  },
  {
    id: 60,
    type: "truth",
    content: "Ai là người dễ được crush nhất?",
  },
  {
    id: 61,
    type: "truth",
    content: "Ai hợp làm KOL nhất?",
  },
  {
    id: 62,
    type: "truth",
    content: "Ai có gu thời trang đỉnh nhất?",
  },
  {
    id: 63,
    type: "truth",
    content: "Ai sẽ là người quên chìa khóa khi đi chơi?",
  },
  {
    id: 64,
    type: "truth",
    content: "Ai dễ bị bắt gặp lướt TikTok lúc 3 giờ sáng nhất?",
  },
  {
    id: 65,
    type: "truth",
    content: "Nếu lập podcast, bạn chọn ai làm host?",
  },
  {
    id: 66,
    type: "truth",
    content: "Ai là người sống 'chữa lành' nhất?",
  },
  {
    id: 67,
    type: "truth",
    content: "Ai sẽ thắng nếu thi uống bia hôm nay?",
  },
  {
    id: 68,
    type: "truth",
    content: "Ai giữ bí mật tốt nhất?",
  },
  {
    id: 69,
    type: "truth",
    content: "Ai có khiếu hài hước tự nhiên nhất?",
  },
  {
    id: 70,
    type: "truth",
    content: "Bạn đã từng mơ thấy ai đó đang có mặt ở đây chưa?",
  },
  {
    id: 71,
    type: "dare",
    content: "Uống bằng tay không thuận.",
  },
  {
    id: 72,
    type: "dare",
    content: "Cụng ly với ba người rồi uống 1ly.",
  },
  {
    id: 73,
    type: "dare",
    content: "Để người bên phải quyết định bạn uống đến khi nói Dừng.",
  },
  {
    id: 74,
    type: "dare",
    content: "Uống đến khi người bên trái nói 'dừng'.",
  },
  {
    id: 75,
    type: "dare",
    content: "Hai người được chỉ định uống chéo tay.",
  },
  {
    id: 76,
    type: "dare",
    content: "Diễn cảnh tỏ tình với chiếc ghế trong 20 giây.",
  },
  {
    id: 77,
    type: "dare",
    content: "Catwalk như người mẫu trên sàn diễn.",
  },
  {
    id: 78,
    type: "dare",
    content: "Nói bằng giọng MC gameshow trong 30 giây.",
  },
  {
    id: 79,
    type: "dare",
    content: "Giả làm người nổi tiếng để cả bàn đoán.",
  },
  {
    id: 80,
    type: "dare",
    content: "Tạo dáng ảnh bìa tạp chí trong 10 giây.",
  },
  {
    id: 81,
    type: "dare",
    content: "Để cả bàn đặt biệt danh mới cho bạn.",
  },
  {
    id: 82,
    type: "dare",
    content: "Đổi chỗ với người được cả bàn chỉ định.",
  },
  {
    id: 83,
    type: "dare",
    content: "Khen người đối diện bằng 5 từ.",
  },
  {
    id: 84,
    type: "dare",
    content: "Để người bên trái chọn ảnh selfie đẹp nhất của bạn (không đăng).",
  },
  {
    id: 85,
    type: "dare",
    content: "Chơi oẳn tù tì với người bên phải, người thua uống.",
  },
  {
    id: 86,
    type: "dare",
    content: "Ôm người được chỉ định trong 15 giây (nếu cả hai đồng ý).",
  },
  {
    id: 87,
    type: "dare",
    content: "Nắm tay người được chỉ định đến hết lượt (nếu cả hai đồng ý).",
  },
  {
    id: 88,
    type: "dare",
    content: "Khoác vai người được chỉ định và chụp một tấm ảnh (nếu đồng ý).",
  },
  {
    id: 89,
    type: "dare",
    content: "Hôn lên trán người được chỉ định (nếu cả hai đồng ý).",
  },
  {
    id: 90,
    type: "dare",
    content: "Chạm trán với người được chỉ định trong 10 giây (nếu cả hai đồng ý).",
  },
  {
    id: 91,
    type: "random",
    content: "Người có pin điện thoại thấp nhất uống.",
  },
  {
    id: 92,
    type: "random",
    content: "Người đến muộn nhất uống.",
  },
  {
    id: 93,
    type: "random",
    content: "Người mặc nhiều màu đen nhất uống.",
  },
  {
    id: 94,
    type: "random",
    content: "Tất cả đổi chỗ ngồi theo chiều kim đồng hồ.",
  },
  {
    id: 95,
    type: "random",
    content: "Cả bàn bình chọn một người uống.",
  },
  {
    id: 96,
    type: "random",
    content: "Tất cả phải dùng tay không thuận trong lượt tiếp theo.",
  },
  {
    id: 97,
    type: "random",
    content: "Choc lét nhau trong 5 giây, ai cười phải uống.",
  },
  {
    id: 98,
    type: "random",
    content: "Mỗi người nói 1 câu tiếng miền/nước khác.",
  },
  {
    id: 99,
    type: "random",
    content: "Người nhỏ tuổi nhất chọn một người cùng uống.",
  },
  {
    id: 100,
    type: "random",
    content: "Tất cả cụng ly rồi uống hết.",
  },
  {
    id: 101,
    type: "truth",
    content: "Ai trong bàn có 'green flag' nhiều nhất?",
  },
  {
    id: 102,
    type: "truth",
    content: "Ai dễ khiến bạn rung động nhất nếu mới gặp hôm nay?",
  },
  {
    id: 103,
    type: "truth",
    content: "Ai có gu người yêu khó đoán nhất?",
  },
  {
    id: 104,
    type: "truth",
    content: "Ai là người có khả năng thả thính giỏi nhất?",
  },
  {
    id: 105,
    type: "truth",
    content: "Nếu phải ghép đôi hai người trong bàn, bạn sẽ ghép ai với ai?",
  },
  {
    id: 106,
    type: "truth",
    content: "Ai là người có nụ cười cuốn hút nhất?",
  },
  {
    id: 107,
    type: "truth",
    content: "Ai có phong cách ăn mặc hợp đi hẹn hò nhất?",
  },
  {
    id: 108,
    type: "truth",
    content: "Khi muốn cảm thấy quyến rũ hơn, bạn thường mặc gì?",
  },
  {
    id: 109,
    type: "truth",
    content: "Ai có ánh mắt 'nguy hiểm' nhất?",
  },
  {
    id: 110,
    type: "truth",
    content: "Ai sẽ là người chủ động nhắn tin trước sau buổi tiệc?",
  },
  {
    id: 111,
    type: "truth",
    content: "Ai có khả năng giữ bình tĩnh khi bị crush nhìn nhất?",
  },
  {
    id: 112,
    type: "truth",
    content: "Câu thả thính táo bạo nhất bạn từng dùng là gì?",
  },
  {
    id: 113,
    type: "truth",
    content: "Lần gần nhất bạn ngạc nhiên vì sự trưởng thành của chính mình là khi nào?",
  },
  {
    id: 114,
    type: "truth",
    content: "Đúng hay sai: Du lịch khiến con người trở nên tốt hơn.",
  },
  {
    id: 115,
    type: "truth",
    content: "Ai là người dễ làm người khác đỏ mặt nhất?",
  },
  {
    id: 116,
    type: "truth",
    content: "Ai có phong cách quyến rũ tự nhiên nhất?",
  },
  {
    id: 117,
    type: "truth",
    content: "Khi ngồi trên bồn cầu, bạn thường nghĩ về điều gì?",
  },
  {
    id: 118,
    type: "truth",
    content: "Ai có khả năng khiến người khác cười khi đang nghiêm túc nhất?",
  },
  {
    id: 119,
    type: "truth",
    content: "Ai sẽ thắng nếu thi tán tỉnh trong 30 giây?",
  },
  {
    id: 120,
    type: "truth",
    content: "Ở thời điểm này, điều gì khiến bạn cảm thấy hào hứng nhất?",
  },
  {
    id: 121,
    type: "dare",
    content: "Để cả bàn chọn: uống 1 ly hoặc nửa ly , bạn phải chấp nhận.",
  },
  {
    id: 122,
    type: "dare",
    content: "Cụng ly với tất cả mọi người rồi uống một ly.",
  },
  {
    id: 123,
    type: "dare",
    content: "Đổi ly với người bên trái trong một lượt rồi uống.",
  },
  {
    id: 124,
    type: "dare",
    content: "Hai người được cả bàn chọn cùng uống chéo tay.",
  },
  {
    id: 125,
    type: "dare",
    content: "Người bên phải đếm đến 5, trong thời gian đó bạn phải uống xong 1 ly.",
  },
  {
    id: 126,
    type: "dare",
    content: "Thả thính bàn chân như đang quay TikTok.",
  },
  {
    id: 127,
    type: "dare",
    content: "Tạo dáng 'ảnh couple' với một cái gối hoặc balo.",
  },
  {
    id: 128,
    type: "dare",
    content: "Diễn cảnh bị crush từ chối trong 20 giây.",
  },
  {
    id: 129,
    type: "dare",
    content: "Nói một câu tỏ tình bằng giọng thật điện ảnh.",
  },
  {
    id: 130,
    type: "dare",
    content: "Đi catwalk và tạo 3 dáng kết thúc.",
  },
  {
    id: 131,
    type: "dare",
    content: "Để cả bàn chọn một biệt danh dùng đến hết game.",
  },
  {
    id: 132,
    type: "dare",
    content: "Nhìn vào mắt người được chỉ định trong 15 giây, ai cười trước uống.",
  },
  {
    id: 133,
    type: "dare",
    content: "Khen ba điểm bạn thích ở người đối diện.",
  },
  {
    id: 134,
    type: "dare",
    content: "Chơi oẳn tù tì với hai người (mỗi người 3 lượt), mỗi lần thua uống một ngụm.",
  },
  {
    id: 135,
    type: "dare",
    content: "Đổi chỗ với người được bình chọn nhiều nhất.",
  },
  {
    id: 136,
    type: "dare",
    content: "Ôm người được chỉ định trong 20 giây nếu cả hai đồng ý, nếu không uống phạt.",
  },
  {
    id: 137,
    type: "dare",
    content: "Khoác vai nhau và chụp một bức ảnh nếu cả hai đồng ý.",
  },
  {
    id: 138,
    type: "dare",
    content: "Nắm tay người được chỉ định đến hết hai lượt nếu cả hai đồng ý.",
  },
  {
    id: 139,
    type: "dare",
    content: "Để người được chỉ định tựa đầu lên vai bạn trong 10 giây nếu cả hai đồng ý.",
  },
  {
    id: 140,
    type: "dare",
    content: "Chạm mũi (nose touch) với người được chỉ định trong 5 giây nếu cả hai đồng ý.",
  },
  {
    id: 141,
    type: "random",
    content: "Cả bàn bình chọn người có outfit đẹp nhất, người thắng chỉ định một người uống.",
  },
  {
    id: 142,
    type: "random",
    content: "Người có pin điện thoại cao nhất uống.",
  },
  {
    id: 143,
    type: "random",
    content: "Trong một lượt tiếp theo, mọi người chỉ được nói bằng 3 từ mỗi lần.",
  },
  {
    id: 144,
    type: "random",
    content: "Người cao nhất uống 1 ly",
  },
  {
    id: 145,
    type: "random",
    content: "Ai đang cầm điện thoại phải uống.",
  },
  {
    id: 146,
    type: "random",
    content: "Người sinh gần hôm nay nhất chọn một người cùng uống.",
  },
  {
    id: 147,
    type: "random",
    content: "Tất cả tạo dáng chụp ảnh nhóm trong 5 giây.",
  },
  {
    id: 148,
    type: "random",
    content: "Hai người ngồi đối diện cùng nhau uống nửa.",
  },
  {
    id: 149,
    type: "random",
    content: "Người mặc nhiều màu trắng nhất uống.",
  },
  {
    id: 150,
    type: "random",
    content: "Lượt kế tiếp người thắng oẳn tù tì được quyền chọn người bắt đầu.",
  },
  {
    id: 151,
    type: "truth",
    content: "Ai trong bàn có khả năng 'fall in love' nhanh nhất?",
  },
  {
    id: 152,
    type: "truth",
    content: "Ai dễ bị dụ tham gia trò điên nhất?",
  },
  {
    id: 153,
    type: "truth",
    content: "Ai là người có 'energy' mạnh nhất khi đi quẩy?",
  },
  {
    id: 154,
    type: "truth",
    content: "Ai có khả năng làm cả bàn cười nhiều nhất?",
  },
  {
    id: 155,
    type: "truth",
    content: "Ai đi size giầy >41 uống",
  },
  {
    id: 156,
    type: "truth",
    content: "Những người mù đường uống 1 ly,",
  },
  {
    id: 157,
    type: "truth",
    content: "Ai có gu chụp ảnh đẹp nhất?",
  },
  {
    id: 158,
    type: "truth",
    content: "Những ai đang dung Android thì uống.",
  },
  {
    id: 159,
    type: "truth",
    content: "Ai có khả năng biến buổi nhậu thành buổi tâm sự?",
  },
  {
    id: 160,
    type: "truth",
    content: "Chọn ra 1 người tốt bụng nhất bàn, người đó sẽ chỉ định người uống.",
  },
  {
    id: 161,
    type: "truth",
    content: "1-2-3 chỉ vào người đang \"sỉnh\" nhất.",
  },
  {
    id: 162,
    type: "truth",
    content: "Những ai đang tập Gym thì uống.",
  },
  {
    id: 163,
    type: "truth",
    content: "Ai có gu chọn quán nhậu tốt nhất?",
  },
  {
    id: 164,
    type: "truth",
    content: "Những ai từng bị phạt do vi pham luật giao thông thì uống.",
  },
  {
    id: 165,
    type: "truth",
    content: "Ly nào còn đầy nhất uống cạn.",
  },
  {
    id: 166,
    type: "truth",
    content: "Chọn 2 người bất kỳ và mời họ 1 ly.",
  },
  {
    id: 167,
    type: "truth",
    content: "Ai là người có ánh nhìn đáng tin nhất?",
  },
  {
    id: 168,
    type: "truth",
    content: "Ai sẽ là người nhảy sung nhất nếu có nhạc?",
  },
  {
    id: 169,
    type: "truth",
    content: "Avatar Facebook nhiều Like nhất thì uống.",
  },
  {
    id: 170,
    type: "truth",
    content: "Ai là người bạn muốn ngồi cạnh nhất trong bữa tiệc?",
  },
  {
    id: 171,
    type: "dare",
    content: "Những ai từng hôn nhau nơi công cộng thì uống 1 ly.",
  },
  {
    id: 172,
    type: "dare",
    content: "Ai nhỏ tuổi nhất thì uống.",
  },
  {
    id: 173,
    type: "dare",
    content: "Những ai họ Nguyễn uống 1 ly.",
  },
  {
    id: 174,
    type: "dare",
    content: "Người nhỏ tuổi nhất quyết định bạn uống hay miễn.",
  },
  {
    id: 175,
    type: "dare",
    content: "Team có gia đình nhỏ và team chưa có gia đình nhỏ, team nào ít hơn thì uống.",
  },
  {
    id: 176,
    type: "dare",
    content: "Diễn cảnh nhận giải Oscar trong 20 giây.",
  },
  {
    id: 177,
    type: "dare",
    content: "1...2...3 Ai đặt 2 tay lên đầu chậm nhất thì uống.",
  },
  {
    id: 178,
    type: "dare",
    content: "Điện thoại ai <50% thì uống,",
  },
  {
    id: 179,
    type: "dare",
    content: "Nói một câu cực 'deep' bằng giọng nghiêm túc.",
  },
  {
    id: 180,
    type: "dare",
    content: "Diễn biểu cảm khi uống phải ly cực đắng.",
  },
  {
    id: 181,
    type: "dare",
    content: "Team iPhone uống 1 ly.",
  },
  {
    id: 182,
    type: "dare",
    content: "Người bên trái bạn hỏi bạn 1 câu hỏi bất kỳ. Bạn chọn trả lời hoặc uống.",
  },
  {
    id: 183,
    type: "dare",
    content: "Khen lần lượt ba người bất kỳ trong bàn.",
  },
  {
    id: 184,
    type: "dare",
    content: "Người cao nhất và người thấp nhất cùng cạn ly.",
  },
  {
    id: 185,
    type: "dare",
    content: "Chọn 1 trong 2 phương án, phe nào ít thì uống: \"Trà Đào\" hay \"Trà Sữa\"",
  },
  {
    id: 186,
    type: "dare",
    content: "Vuốt tay rồi nắm tay người được chỉ định 10 giây nếu cả hai đồng ý.",
  },
  {
    id: 187,
    type: "dare",
    content: "Khoác vai và cùng nói: Đêm qua em thật tuyệt vời.",
  },
  {
    id: 188,
    type: "dare",
    content: "Ôm vai chụp ảnh với người được chỉ định nếu cả hai đồng ý.",
  },
  {
    id: 189,
    type: "dare",
    content: "Chạm trán trong 10 giây nếu cả hai đồng ý.",
  },
  {
    id: 190,
    type: "dare",
    content: "Đan tay với người được chỉ định đến hết lượt nếu cả hai đồng ý.",
  },
  {
    id: 191,
    type: "random",
    content: "Người có tên dài nhất uống.",
  },
  {
    id: 192,
    type: "random",
    content: "Người có ít pin nhất được miễn, người nhiều pin nhất uống.",
  },
  {
    id: 193,
    type: "random",
    content: "Nếu cuộc đời được làm lại một lần, bạn sẽ chọn quay về khoảnh khắc nào?",
  },
  {
    id: 194,
    type: "random",
    content: "Bắt chước một người trong phòng cho đến khi có người đoán ra.",
  },
  {
    id: 195,
    type: "random",
    content: "2 người bên cạnh người bốc lá bài này phải uống",
  },
  {
    id: 196,
    type: "random",
    content: "Người cầm ly bằng tay trái uống.",
  },
  {
    id: 197,
    type: "random",
    content: "Người cao nhất chọn người bắt đầu lượt tiếp theo.",
  },
  {
    id: 198,
    type: "random",
    content: "Ai nhìn điện thoại đầu tiên phải uống.",
  },
  {
    id: 199,
    type: "random",
    content: "Tuyệt vời. Bạn thật may mắn. Bạn được PASS và lượt sau nếu bị uống thì bạn chỉ định ai uống thay bạn",
  },
  {
    id: 200,
    type: "random",
    content: "Chơi nối từ, người cuối cùng \"bí\" thì uống",
  },
  {
    id: 201,
    type: "truth",
    content: "Ai trong bàn có khả năng tán đổ người khác nhanh nhất?",
  },
  {
    id: 202,
    type: "truth",
    content: "Ai có gu nhắn tin 'mập mờ' nhất?",
  },
  {
    id: 203,
    type: "truth",
    content: "Chơi nối từ, ai thua thì uống.",
  },
  {
    id: 204,
    type: "truth",
    content: "Ai có khả năng giữ bình tĩnh khi bị trêu nhất?",
  },
  {
    id: 205,
    type: "truth",
    content: "Ai có gu chụp ảnh đôi đẹp nhất?",
  },
  {
    id: 206,
    type: "truth",
    content: "Ai là người bạn sẽ rủ đi roadtrip đầu tiên?",
  },
  {
    id: 207,
    type: "truth",
    content: "Ai dễ trở thành linh hồn của bữa tiệc nhất?",
  },
  {
    id: 208,
    type: "truth",
    content: "Ai sẽ là người chủ động xin lỗi trước?",
  },
  {
    id: 209,
    type: "truth",
    content: "Ai có phong cách sống đáng học hỏi nhất?",
  },
  {
    id: 210,
    type: "truth",
    content: "Ai có khiếu kể chuyện nhất?",
  },
  {
    id: 211,
    type: "truth",
    content: "Ai từng dùng Tinder thì uống",
  },
  {
    id: 212,
    type: "truth",
    content: "Bật đèn hay tắt đèn",
  },
  {
    id: 213,
    type: "truth",
    content: "Ai dễ được giao giữ bí mật nhất?",
  },
  {
    id: 214,
    type: "truth",
    content: "Ai lên kế hoạch chuyến đi tốt nhất?",
  },
  {
    id: 215,
    type: "truth",
    content: "Ai khiến người khác cười chỉ bằng một câu nói?",
  },
  {
    id: 216,
    type: "truth",
    content: "Vỗ mông người bên cạnh bạn",
  },
  {
    id: 217,
    type: "truth",
    content: "Ai có khả năng trở thành streamer nhất?",
  },
  {
    id: 218,
    type: "truth",
    content: "Ai là người bạn muốn ngồi nhậu thêm một vòng?",
  },
  {
    id: 219,
    type: "truth",
    content: "Nếu được chọn 1 phẩm chất của 1 người trong nhóm bạn sẽ chọn gì và của ai",
  },
  {
    id: 220,
    type: "truth",
    content: "Ai đã từng stalk người khác trên mạng xã hội thì uống",
  },
  {
    id: 221,
    type: "dare",
    content: "Thẻ quyền lực- Chọn một người và được đặt ra một câu hỏi cho người đó",
  },
  {
    id: 222,
    type: "dare",
    content: "Bạn sẽ làm gì khi hết giấy vệ sinh?",
  },
  {
    id: 223,
    type: "dare",
    content: "Ra ngoài sân hét lớn: \"Tui là con hêuuuu\"",
  },
  {
    id: 224,
    type: "dare",
    content: "Để cả bàn vote: uống hoặc miễn, theo đa số.",
  },
  {
    id: 225,
    type: "dare",
    content: "Uống nửa ly rồi hô 'Tẹt dời!'.",
  },
  {
    id: 226,
    type: "dare",
    content: "Diễn cảnh được cầu hôn trong phim.",
  },
  {
    id: 227,
    type: "dare",
    content: "Quảng cáo món nhậu trên bàn trong 20 giây.",
  },
  {
    id: 228,
    type: "dare",
    content: "Bịt mắt, để mọi người đút cho bạn ăn một món và đoán đó là gì",
  },
  {
    id: 229,
    type: "dare",
    content: "Giả tiếng kêu 1 loài động vật.",
  },
  {
    id: 230,
    type: "dare",
    content: "Bịt mắt, sờ mặt mọi người và đoán xem là ai.",
  },
  {
    id: 231,
    type: "dare",
    content: "Thực hiện 20 lần squat.",
  },
  {
    id: 232,
    type: "dare",
    content: "Nói ra điểm thu hút nhất của mỗi người trong phòng theo cảm nhận của bạn.",
  },
  {
    id: 233,
    type: "dare",
    content: "Đổi chỗ với người được vote nhiều nhất.",
  },
  {
    id: 234,
    type: "dare",
    content: "Mỗi người nói một điểm họ thích ở bạn.",
  },
  {
    id: 235,
    type: "dare",
    content: "Bạn chọn hai người cụng ly với nhau.",
  },
  {
    id: 236,
    type: "dare",
    content: "Khoác vai người được chỉ định 15 giây nếu cả hai đồng ý.",
  },
  {
    id: 237,
    type: "dare",
    content: "Ôm vai chụp ảnh cùng nếu cả hai đồng ý.",
  },
  {
    id: 238,
    type: "dare",
    content: "Hun vào bụng dưới của người đối diện.",
  },
  {
    id: 239,
    type: "dare",
    content: "Chạm trán và cùng hô \"Chụt chụt\".",
  },
  {
    id: 240,
    type: "dare",
    content: "Liếm trái tai của người đối diện.",
  },
  {
    id: 241,
    type: "random",
    content: "Vote: Cả bàn bình chọn người có outfit đẹp nhất, người thắng chỉ định một người uống.",
  },
  {
    id: 242,
    type: "random",
    content: "King: Người vừa hoàn thành lượt được quyền chọn người chơi tiếp theo.",
  },
  {
    id: 243,
    type: "random",
    content: "Pair: Hai người ngồi đối diện phải cùng thực hiện lượt kế tiếp.",
  },
  {
    id: 244,
    type: "random",
    content: "Happy Hour: Tất cả cùng uống một ngụm.",
  },
  {
    id: 245,
    type: "random",
    content: "Freeze: Ai cười đầu tiên trong 10 giây phải uống.",
  },
  {
    id: 246,
    type: "random",
    content: "Ra ngoài tru lên với mặt trăng.",
  },
  {
    id: 247,
    type: "random",
    content: "Người lớn tuổi nhất chọn người mở lượt tiếp theo.",
  },
  {
    id: 248,
    type: "random",
    content: "Người vừa mở điện thoại gần nhất uống.",
  },
  {
    id: 249,
    type: "random",
    content: "Cả bàn chụp một ảnh nhóm với biểu cảm ngẫu nhiên.",
  },
  {
    id: 250,
    type: "random",
    content: "Mỗi người khen người bên phải một câu.",
  },
  {
    id: 251,
    type: "truth",
    content: "Ai trong bàn có khả năng tán đổ người khác nhanh nhất?",
  },
  {
    id: 252,
    type: "truth",
    content: "Ai có gu nhắn tin 'mập mờ' nhất?",
  },
  {
    id: 253,
    type: "truth",
    content: "Chơi nối từ, ai thua thì uống.",
  },
  {
    id: 254,
    type: "truth",
    content: "Ai có khả năng giữ bình tĩnh khi bị trêu nhất?",
  },
  {
    id: 255,
    type: "truth",
    content: "Ai có gu chụp ảnh đôi đẹp nhất?",
  },
  {
    id: 256,
    type: "truth",
    content: "Ai là người bạn sẽ rủ đi roadtrip đầu tiên?",
  },
  {
    id: 257,
    type: "truth",
    content: "Ai dễ trở thành linh hồn của bữa tiệc nhất?",
  },
  {
    id: 258,
    type: "truth",
    content: "Ai sẽ là người chủ động xin lỗi trước?",
  },
  {
    id: 259,
    type: "truth",
    content: "Ai có phong cách sống đáng học hỏi nhất?",
  },
  {
    id: 260,
    type: "truth",
    content: "Ai có khiếu kể chuyện nhất?",
  },
  {
    id: 261,
    type: "truth",
    content: "Ai từng dùng Tinder thì uống",
  },
  {
    id: 262,
    type: "truth",
    content: "Bật đèn hay tắt đèn",
  },
  {
    id: 263,
    type: "truth",
    content: "Ai dễ được giao giữ bí mật nhất?",
  },
  {
    id: 264,
    type: "truth",
    content: "Ai lên kế hoạch chuyến đi tốt nhất?",
  },
  {
    id: 265,
    type: "truth",
    content: "Ai khiến người khác cười chỉ bằng một câu nói?",
  },
  {
    id: 266,
    type: "truth",
    content: "Vỗ mông người bên cạnh bạn",
  },
  {
    id: 267,
    type: "truth",
    content: "Ai có khả năng trở thành streamer nhất?",
  },
  {
    id: 268,
    type: "truth",
    content: "Ai là người bạn muốn ngồi nhậu thêm một vòng?",
  },
  {
    id: 269,
    type: "truth",
    content: "Nếu được chọn 1 phẩm chất của 1 người trong nhóm bạn sẽ chọn gì và của ai",
  },
  {
    id: 270,
    type: "truth",
    content: "Ai đã từng stalk người khác trên mạng xã hội thì uống",
  },
  {
    id: 271,
    type: "dare",
    content: "Thẻ quyền lực- Chọn một người và được đặt ra một câu hỏi cho người đó",
  },
  {
    id: 272,
    type: "dare",
    content: "Bạn sẽ làm gì khi hết giấy vệ sinh?",
  },
  {
    id: 273,
    type: "dare",
    content: "Ra ngoài sân hét lớn: \"Tui là con hêuuuu\"",
  },
  {
    id: 274,
    type: "dare",
    content: "Để cả bàn vote: uống hoặc miễn, theo đa số.",
  },
  {
    id: 275,
    type: "dare",
    content: "Uống nửa ly rồi hô 'Tẹt dời!'.",
  },
  {
    id: 276,
    type: "dare",
    content: "Diễn cảnh được cầu hôn trong phim.",
  },
  {
    id: 277,
    type: "dare",
    content: "Quảng cáo món nhậu trên bàn trong 20 giây.",
  },
  {
    id: 278,
    type: "dare",
    content: "Bịt mắt, để mọi người đút cho bạn ăn một món và đoán đó là gì",
  },
  {
    id: 279,
    type: "dare",
    content: "Giả tiếng kêu 1 loài động vật.",
  },
  {
    id: 280,
    type: "dare",
    content: "Bịt mắt, sờ mặt mọi người và đoán xem là ai.",
  },
  {
    id: 281,
    type: "dare",
    content: "Thực hiện 20 lần squat.",
  },
  {
    id: 282,
    type: "dare",
    content: "Nói ra điểm thu hút nhất của mỗi người trong phòng theo cảm nhận của bạn.",
  },
  {
    id: 283,
    type: "dare",
    content: "Đổi chỗ với người được vote nhiều nhất.",
  },
  {
    id: 284,
    type: "dare",
    content: "Mỗi người nói một điểm họ thích ở bạn.",
  },
  {
    id: 285,
    type: "dare",
    content: "Bạn chọn hai người cụng ly với nhau.",
  },
  {
    id: 286,
    type: "dare",
    content: "Khoác vai người được chỉ định 15 giây nếu cả hai đồng ý.",
  },
  {
    id: 287,
    type: "dare",
    content: "Ôm vai chụp ảnh cùng nếu cả hai đồng ý.",
  },
  {
    id: 288,
    type: "dare",
    content: "Hun vào bụng dưới của người đối diện.",
  },
  {
    id: 289,
    type: "dare",
    content: "Chạm trán và cùng hô \"Chụt chụt\".",
  },
  {
    id: 290,
    type: "dare",
    content: "Liếm trái tai của người đối diện.",
  },
  {
    id: 291,
    type: "random",
    content: "Vote: Cả bàn bình chọn người có outfit đẹp nhất, người thắng chỉ định một người uống.",
  },
  {
    id: 292,
    type: "random",
    content: "King: Người vừa hoàn thành lượt được quyền chọn người chơi tiếp theo.",
  },
  {
    id: 293,
    type: "random",
    content: "Pair: Hai người ngồi đối diện phải cùng thực hiện lượt kế tiếp.",
  },
  {
    id: 294,
    type: "random",
    content: "Happy Hour: Tất cả cùng uống một ngụm.",
  },
  {
    id: 295,
    type: "random",
    content: "Freeze: Ai cười đầu tiên trong 10 giây phải uống.",
  },
  {
    id: 296,
    type: "random",
    content: "Ra ngoài tru lên với mặt trăng.",
  },
  {
    id: 297,
    type: "random",
    content: "Người lớn tuổi nhất chọn người mở lượt tiếp theo.",
  },
  {
    id: 298,
    type: "random",
    content: "Người vừa mở điện thoại gần nhất uống.",
  },
  {
    id: 299,
    type: "random",
    content: "Cả bàn chụp một ảnh nhóm với biểu cảm ngẫu nhiên.",
  },
  {
    id: 300,
    type: "random",
    content: "Mỗi người khen người bên phải một câu.",
  },
];
